<?php
namespace app\controllers\base;

use Yii;
use yii\web\Controller;

class SecuredController extends Controller
{
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['auth/login']);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}